(* [pol] — the standalone command line. This module is now only the dispatch:
   the argument shapes each verb accepts, and what a misuse costs. The verbs
   themselves live in [Cmd_check], [Cmd_query], [Cmd_compare], [Cmd_control]
   and [Cmd_derive];
   the filesystem they share lives in [Cli_io]; [Help] holds the --help text and
   [Version] is generated by dune. The split is deliberate — a dispatch that
   also implements every verb is a file that grows without bound, and this one
   had reached the size where the next verb would not fit.

   The command line is still the ONLY module tree with I/O besides the LSP
   process; everything below returns values and strings, which is what keeps the
   engine testable without a filesystem. It links the three engine libraries —
   [Pol_data] (the data model), [Pol_syntax] (the front end), and [Pol_runtime]
   (the interrogator).

   Exit status is the interface (kernel §18): 0 = answered, nothing failed;
   1 = a finding (a failed property, or a violated / unadmitted / stale law);
   2 = unreadable input (a missing file, a parse error, or a bad command line).

   The [(load "FILE")] resolver is built in [Cli_io], over the search order in
   [Pol_loadpath] (design D3) that the LSP process shares; there is no implicit
   prelude. *)

open Cli_io

(* The misuse message, derived from [Help.verbs] rather than written again:
   the two lists had no way to stay in step except attention, which is the same
   argument [Version] makes about a hand-kept version number. *)
let usage =
  String.concat "\n"
    ("usage:"
     :: List.concat_map
          (fun (v : Help.verb) -> List.map (fun u -> "  " ^ u) v.usage)
          Help.verbs
    @ [
        "  pol help VERB | pol VERB --help";
        "  pol --help | -h";
        "  pol --version | -V";
      ])

(* [pol], [pol -h], [pol --help] and [pol help] print the full help and exit 0;
   a misuse prints the short [usage] to stderr and exits 2. *)
let help () =
  print_string Help.text;
  exit 0

(* [Version.v] is generated by dune from the package version in dune-project, so
   the binary, the opam package and the release tarball cannot disagree about
   which pol this is — the first question asked of any installed tool, and the
   one a hand-maintained constant always eventually answers wrongly. *)
let version () =
  say ("pol " ^ Version.v);
  say "Copyright (C) 2026 Alex Kunich.  License AGPL-3.0-or-later.";
  say "This is free software: you are free to change and redistribute it.";
  say "There is NO WARRANTY, to the extent permitted by law.";
  exit 0

(* One verb's help. Both spellings work because both are guessed: `pol help
   sql` by anyone who read the usage line, `pol sql --help` by everyone else,
   who tries it on the verb they are already typing. *)
let verb_help (name : string) =
  match Help.for_verb name with
  | Some t ->
      print_string t;
      exit 0
  | None -> die 2 ("no such verb `" ^ name ^ "`\n" ^ usage)

let () =
  match Array.to_list Sys.argv with
  | [ _ ] | [ _; ("-h" | "--help" | "help") ] -> help ()
  | [ _; ("-V" | "--version" | "version") ] -> version ()
  (* before the verbs, so `pol schema --help` is a question and not a file
     named `--help` *)
  | [ _; "help"; v ] | [ _; v; ("-h" | "--help") ] -> verb_help v
  | _ :: "check" :: model :: rest -> (
      match rest with
      | [] -> Cmd_check.run model None
      | [ "--claims"; c ] -> Cmd_check.run model (Some c)
      | _ -> die 2 usage)
  | _ :: "query" :: model :: name :: rest -> (
      match rest with
      | [] -> Cmd_query.run model name None
      | [ "--at"; s ] -> Cmd_query.run model name (Some s)
      | _ -> die 2 usage)
  | [ _; "control"; model ] -> Cmd_control.run model
  | [ _; "schema"; model ] -> Cmd_schema.run model
  | _ :: "sql" :: file :: rest ->
      (* the direction is the extension, so the flags are the only options and
         either order will do *)
      let known = [ "--with-data"; "--strict" ] in
      if List.exists (fun f -> not (List.mem f known)) rest then die 2 usage
      else
        Cmd_sql.run file
          ~with_data:(List.mem "--with-data" rest)
          ~strict:(List.mem "--strict" rest)
  | _ :: "derive" :: model :: rules :: rest -> (
      match rest with
      | [ q ] -> Cmd_derive.run model rules ~why:false q
      | [ "--why"; q ] -> Cmd_derive.run model rules ~why:true q
      | _ -> die 2 usage)
  | _ :: "compare" :: rest -> (
      match rest with
      | "--git" :: r1 :: r2 :: model :: mrest -> (
          match mrest with
          | [] -> Cmd_compare.run_git r1 r2 model None
          | [ "--map"; mp ] -> Cmd_compare.run_git r1 r2 model (Some mp)
          | _ -> die 2 usage)
      | old_p :: new_p :: mrest -> (
          match mrest with
          | [] -> Cmd_compare.run old_p new_p None
          | [ "--map"; mp ] -> Cmd_compare.run old_p new_p (Some mp)
          | _ -> die 2 usage)
      | _ -> die 2 usage)
  | _ -> die 2 usage
