(* Copyright (C) 2026 Alex Kunich *)
(* SPDX-License-Identifier: AGPL-3.0-or-later *)

(* The [writ] command line: argument dispatch only. Each verb lives in a
   [Cmd_*] module, shared I/O in [Cli_io], help text in [Help]. Besides the LSP,
   this is the only code with I/O; the engine below returns values. Exit status
   is described in [Cli_io] (kernel §18). *)

open Cli_io

(* The misuse message, derived from [Help.verbs]. *)
let usage =
  String.concat "\n"
    ("usage:"
     :: List.concat_map
          (fun (v : Help.verb) -> List.map (fun u -> "  " ^ u) v.usage)
          Help.verbs
    @ [
        "  writ help VERB | writ VERB --help";
        "  writ --help | -h";
        "  writ --version | -V | -v";
      ])

(* Full help exits 0; a misuse prints [usage] to stderr and exits 2. *)
let help () =
  print_string Help.text;
  exit 0

(* [Version.v] is generated by dune from dune-project. *)
let version () =
  say ("writ " ^ Version.v);
  say "Copyright (C) 2026 Alex Kunich.  License AGPL-3.0-or-later.";
  say "This is free software: you are free to change and redistribute it.";
  say "There is NO WARRANTY, to the extent permitted by law.";
  exit 0

(* One verb's help, as `writ help VERB` or `writ VERB --help`. *)
let verb_help (name : string) =
  match Help.for_verb name with
  | Some t ->
      print_string t;
      exit 0
  | None -> die 2 ("no such verb `" ^ name ^ "`\n" ^ usage)

let () =
  match Array.to_list Sys.argv with
  | [ _ ] | [ _; ("-h" | "--help" | "help") ] -> help ()
  (* `-v` too: writ has no verbosity flag to reserve it for. *)
  | [ _; ("-V" | "-v" | "--version" | "version") ] -> version ()
  (* before the verbs, so `writ schema --help` is a question and not a file
     named `--help` *)
  | [ _; "help"; v ] | [ _; v; ("-h" | "--help") ] -> verb_help v
  (* Every verb strips [--stdin] before counting positionals, then passes
     [Cli_io.stdin_name] in the model slot; no verb knows stdin exists. *)
  | _ :: "check" :: rest -> (
      let json, rest = Writ_dispatch.take_json rest in
      let certificate, rest = Writ_dispatch.take_certificate rest in
      let off, rest = Writ_dispatch.take_no_certificate rest in
      (* on by default; a named file wins over the default place *)
      let certificate =
        match (off, certificate) with
        | true, _ -> Cmd_check.Off
        | false, Some f -> Cmd_check.To f
        | false, None -> Cmd_check.Beside
      in
      let version = Version.v in
      let fibers, rest = Writ_dispatch.take_fibers rest in
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, [] ->
          Cmd_check.run ~json ~fibers ~certificate ~version Cli_io.stdin_name
            None
      | true, [ "--claims"; c ] ->
          Cmd_check.run ~json ~fibers ~certificate ~version Cli_io.stdin_name
            (Some c)
      | false, [ model ] ->
          Cmd_check.run ~json ~fibers ~certificate ~version model None
      | false, [ model; "--claims"; c ] ->
          Cmd_check.run ~json ~fibers ~certificate ~version model (Some c)
      | _ -> die 2 usage)
  | _ :: "query" :: rest -> (
      let json, rest = Writ_dispatch.take_json rest in
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      let claims, rest = Writ_dispatch.take_claims rest in
      match (stdin_, rest) with
      | true, [ name ] ->
          Cmd_query.run ~json ~claims Cli_io.stdin_name name None
      | true, [ name; "--at"; s ] ->
          Cmd_query.run ~json ~claims Cli_io.stdin_name name (Some s)
      | false, [ model; name ] -> Cmd_query.run ~json ~claims model name None
      | false, [ model; name; "--at"; s ] ->
          Cmd_query.run ~json ~claims model name (Some s)
      | _ -> die 2 usage)
  | _ :: "show" :: rest -> (
      let json, rest = Writ_dispatch.take_json rest in
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, flags -> Cmd_show.run ~json Cli_io.stdin_name flags
      | false, model :: flags -> Cmd_show.run ~json model flags
      | false, [] -> die 2 usage)
  | _ :: "graph" :: rest -> (
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, flags -> Cmd_graph.run Cli_io.stdin_name flags
      | false, model :: flags -> Cmd_graph.run model flags
      | false, [] -> die 2 usage)
  | _ :: "control" :: rest -> (
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, [] -> Cmd_control.run Cli_io.stdin_name
      | false, [ model ] -> Cmd_control.run model
      | _ -> die 2 usage)
  | _ :: "schema" :: rest -> (
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, [] -> Cmd_schema.run Cli_io.stdin_name
      | false, [ model ] -> Cmd_schema.run model
      | _ -> die 2 usage)
  | _ :: "sql" :: file :: rest ->
      (* the direction is the extension, so the flags are the only options and
         either order will do *)
      let known = [ "--with-data"; "--strict" ] in
      if List.exists (fun f -> not (List.mem f known)) rest then die 2 usage
      else
        Cmd_sql.run file
          ~with_data:(List.mem "--with-data" rest)
          ~strict:(List.mem "--strict" rest)
  | _ :: "derive" :: rest -> (
      let json, rest = Writ_dispatch.take_json rest in
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, [ rules; q ] ->
          Cmd_derive.run ~json Cli_io.stdin_name rules ~why:false q
      | true, [ rules; "--why"; q ] ->
          Cmd_derive.run ~json Cli_io.stdin_name rules ~why:true q
      | false, [ model; rules; q ] ->
          Cmd_derive.run ~json model rules ~why:false q
      | false, [ model; rules; "--why"; q ] ->
          Cmd_derive.run ~json model rules ~why:true q
      | _ -> die 2 usage)
  | _ :: "compare" :: rest -> (
      let json, rest = Writ_dispatch.take_json rest in
      match rest with
      (* revisions are read from git, so there is no stdin to take *)
      | "--git" :: r1 :: r2 :: model :: mrest -> (
          if List.mem "--stdin" mrest then
            die 2 "compare --git takes no --stdin\n"
          else
            match mrest with
            | [] -> Cmd_compare.run_git ~json r1 r2 model None
            | [ "--map"; mp ] -> Cmd_compare.run_git ~json r1 r2 model (Some mp)
            | _ -> die 2 usage)
      (* --stdin fills the NEW side, so it must follow the old model; otherwise
         both orders strip to one positional and one compares backwards. *)
      | "--stdin" :: _ ->
          die 2
            "compare: --stdin fills the NEW side, so it follows the old model:\n\
            \  writ compare OLD.writ --stdin\n"
      | old_p :: mrest -> (
          let stdin_, mrest = Writ_dispatch.take_stdin mrest in
          match (stdin_, mrest) with
          | true, [] -> Cmd_compare.run ~json old_p Cli_io.stdin_name None
          | true, [ "--map"; mp ] ->
              Cmd_compare.run ~json old_p Cli_io.stdin_name (Some mp)
          | false, [ new_p ] -> Cmd_compare.run ~json old_p new_p None
          | false, [ new_p; "--map"; mp ] ->
              Cmd_compare.run ~json old_p new_p (Some mp)
          | _ -> die 2 usage)
      | _ -> die 2 usage)
  | _ -> die 2 usage
