(* Copyright (C) 2026 Alex Kunich *)
(* SPDX-License-Identifier: AGPL-3.0-or-later *)

(* [writ] — the standalone command line. This module is now only the dispatch:
   the argument shapes each verb accepts, and what a misuse costs. The verbs
   themselves live in [Cmd_check], [Cmd_query], [Cmd_compare], [Cmd_control]
   and [Cmd_derive];
   the filesystem they share lives in [Cli_io]; [Help] holds the --help text and
   [Version] is generated by dune. The split is deliberate — a dispatch that
   also implements every verb is a file that grows without bound, and this one
   had reached the size where the next verb would not fit.

   The command line is still the ONLY module tree with I/O besides the LSP
   process; everything below returns values and strings, which is what keeps the
   engine testable without a filesystem. It links the three engine libraries —
   [Writ_data] (the data model), [Writ_syntax] (the front end), and [Writ_runtime]
   (the interrogator).

   Exit status is the interface (kernel §18): 0 = answered, nothing failed;
   1 = a finding (a failed property, or a violated / unadmitted / stale law);
   2 = unreadable input (a missing file, a parse error, or a bad command line).

   The [(load "FILE")] resolver is built in [Cli_io], over the search order in
   [Writ_loadpath] (design D3) that the LSP process shares; there is no implicit
   prelude. *)

open Cli_io

(* The misuse message, derived from [Help.verbs] rather than written again:
   the two lists had no way to stay in step except attention, which is the same
   argument [Version] makes about a hand-kept version number. *)
let usage =
  String.concat "\n"
    ("usage:"
     :: List.concat_map
          (fun (v : Help.verb) -> List.map (fun u -> "  " ^ u) v.usage)
          Help.verbs
    @ [
        "  writ help VERB | writ VERB --help";
        "  writ --help | -h";
        "  writ --version | -V | -v";
      ])

(* [writ], [writ -h], [writ --help] and [writ help] print the full help and exit 0;
   a misuse prints the short [usage] to stderr and exits 2. *)
let help () =
  print_string Help.text;
  exit 0

(* [Version.v] is generated by dune from the package version in dune-project, so
   the binary, the opam package and the release tarball cannot disagree about
   which writ this is — the first question asked of any installed tool, and the
   one a hand-maintained constant always eventually answers wrongly. *)
let version () =
  say ("writ " ^ Version.v);
  say "Copyright (C) 2026 Alex Kunich.  License AGPL-3.0-or-later.";
  say "This is free software: you are free to change and redistribute it.";
  say "There is NO WARRANTY, to the extent permitted by law.";
  exit 0

(* One verb's help. Both spellings work because both are guessed: `writ help
   sql` by anyone who read the usage line, `writ sql --help` by everyone else,
   who tries it on the verb they are already typing. *)
let verb_help (name : string) =
  match Help.for_verb name with
  | Some t ->
      print_string t;
      exit 0
  | None -> die 2 ("no such verb `" ^ name ^ "`\n" ^ usage)

let () =
  match Array.to_list Sys.argv with
  | [ _ ] | [ _; ("-h" | "--help" | "help") ] -> help ()
  (* `-v` as well as `-V`: it is what nearly every tool means by the short
     flag, it is what a hand reaches for, and writ has no verbosity setting to
     want it back (tracing is WRIT_TRACE_LOADS). Getting the usage block instead
     of a version is a papercut with no argument behind it. *)
  | [ _; ("-V" | "-v" | "--version" | "version") ] -> version ()
  (* before the verbs, so `writ schema --help` is a question and not a file
     named `--help` *)
  | [ _; "help"; v ] | [ _; v; ("-h" | "--help") ] -> verb_help v
  (* [--stdin] comes out of the arguments BEFORE the positionals are counted,
     in every verb below. That order is what makes the flag decidable where a
     bare verb would not be: `query`, `derive` and `compare` all take further
     positionals after the model, so dropping it silently would shift the rest
     left. With the flag stripped the remaining arity is fixed, and the
     sentinel [Cli_io.stdin_name] goes into the model slot the verb already
     has — no verb, and nothing in the engine, learns that stdin exists. *)
  | _ :: "check" :: rest -> (
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, [] -> Cmd_check.run Cli_io.stdin_name None
      | true, [ "--claims"; c ] -> Cmd_check.run Cli_io.stdin_name (Some c)
      | false, [ model ] -> Cmd_check.run model None
      | false, [ model; "--claims"; c ] -> Cmd_check.run model (Some c)
      | _ -> die 2 usage)
  | _ :: "query" :: rest -> (
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      let claims, rest = Writ_dispatch.take_claims rest in
      match (stdin_, rest) with
      | true, [ name ] -> Cmd_query.run ~claims Cli_io.stdin_name name None
      | true, [ name; "--at"; s ] ->
          Cmd_query.run ~claims Cli_io.stdin_name name (Some s)
      | false, [ model; name ] -> Cmd_query.run ~claims model name None
      | false, [ model; name; "--at"; s ] ->
          Cmd_query.run ~claims model name (Some s)
      | _ -> die 2 usage)
  | _ :: "show" :: rest -> (
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, flags -> Cmd_show.run Cli_io.stdin_name flags
      | false, model :: flags -> Cmd_show.run model flags
      | false, [] -> die 2 usage)
  | _ :: "control" :: rest -> (
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, [] -> Cmd_control.run Cli_io.stdin_name
      | false, [ model ] -> Cmd_control.run model
      | _ -> die 2 usage)
  | _ :: "schema" :: rest -> (
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, [] -> Cmd_schema.run Cli_io.stdin_name
      | false, [ model ] -> Cmd_schema.run model
      | _ -> die 2 usage)
  | _ :: "sql" :: file :: rest ->
      (* the direction is the extension, so the flags are the only options and
         either order will do *)
      let known = [ "--with-data"; "--strict" ] in
      if List.exists (fun f -> not (List.mem f known)) rest then die 2 usage
      else
        Cmd_sql.run file
          ~with_data:(List.mem "--with-data" rest)
          ~strict:(List.mem "--strict" rest)
  | _ :: "mgtt" :: file :: rest ->
      (* one direction, so --strict is the only option *)
      let known = [ "--strict" ] in
      if List.exists (fun f -> not (List.mem f known)) rest then die 2 usage
      else Cmd_mgtt.run file ~strict:(List.mem "--strict" rest)
  | _ :: "derive" :: rest -> (
      let stdin_, rest = Writ_dispatch.take_stdin rest in
      match (stdin_, rest) with
      | true, [ rules; q ] ->
          Cmd_derive.run Cli_io.stdin_name rules ~why:false q
      | true, [ rules; "--why"; q ] ->
          Cmd_derive.run Cli_io.stdin_name rules ~why:true q
      | false, [ model; rules; q ] -> Cmd_derive.run model rules ~why:false q
      | false, [ model; rules; "--why"; q ] ->
          Cmd_derive.run model rules ~why:true q
      | _ -> die 2 usage)
  | _ :: "compare" :: rest -> (
      match rest with
      (* revisions are read from git, so there is no stdin to take *)
      | "--git" :: r1 :: r2 :: model :: mrest -> (
          if List.mem "--stdin" mrest then
            die 2 "compare --git takes no --stdin\n"
          else
            match mrest with
            | [] -> Cmd_compare.run_git r1 r2 model None
            | [ "--map"; mp ] -> Cmd_compare.run_git r1 r2 model (Some mp)
            | _ -> die 2 usage)
      (* the one rule: --stdin fills the NEW side, so it must FOLLOW the old
         model. `writ compare --stdin baseline.writ` and `writ compare
         baseline.writ --stdin` would otherwise strip to the same one
         positional, and one of the two would silently compare backwards. *)
      | "--stdin" :: _ ->
          die 2
            "compare: --stdin fills the NEW side, so it follows the old model:\n\
            \  writ compare OLD.writ --stdin\n"
      | old_p :: mrest -> (
          let stdin_, mrest = Writ_dispatch.take_stdin mrest in
          match (stdin_, mrest) with
          | true, [] -> Cmd_compare.run old_p Cli_io.stdin_name None
          | true, [ "--map"; mp ] ->
              Cmd_compare.run old_p Cli_io.stdin_name (Some mp)
          | false, [ new_p ] -> Cmd_compare.run old_p new_p None
          | false, [ new_p; "--map"; mp ] ->
              Cmd_compare.run old_p new_p (Some mp)
          | _ -> die 2 usage)
      | _ -> die 2 usage)
  | _ -> die 2 usage
